# Eindtoets NumPy — Missie Mars 🔴

**Welkom bij het controlecentrum van de Mars-kolonie "Ares Base"!**

Het jaar is 2087. Jij bent de data-analist van de eerste permanente Mars-kolonie. De kolonie bestaat uit meerdere modules (woonunits, laboratoria, kassen, energiecentrales) en jij bent verantwoordelijk voor het analyseren van alle sensordata met NumPy.

Gebruik **alleen NumPy** (geen Pandas, geen loops tenzij expliciet gevraagd).

**Onderwerpen die aan bod komen:**
- Broadcasting & element-wise operaties
- np.indices & memory order
- Boolean masks & np.where
- Fancy indexing & np.add.at
- Sorting & partitioning
- Structured arrays, subarrays & RecordArrays

---

```python
import numpy as np
rng = np.random.default_rng(2087)  # vaste seed voor reproduceerbaarheid
```

In [2]:
import numpy as np
rng = np.random.default_rng(2087) # dit is boilerplate code, geen actie vereist. gebruik deze random generator voor de rest van de oefeningen

---
## Deel 1: De Kolonie in Kaart (np.indices & broadcasting)

De Mars-kolonie is gebouwd als een raster van **5 rijen x 6 kolommen** modules. Elke module heeft een positie `(rij, kolom)` in het raster. Het controlecentrum staat op positie `(2, 3)` (midden van het raster).

### Oefening 1.1 — Raster genereren
Gebruik `np.indices` om twee arrays te genereren: een met de **rij-indices** en een met de **kolom-indices** voor het 5x6 raster. Sla ze op in variabelen `rijen` en `kolommen`.

Print de shape van het resultaat.

In [3]:
# 1. Generate the indices map
indices = np.indices((5, 6))

# 2. Save them into the required variables
rijen = indices[0]
kolommen = indices[1]

# 3. Print the content (as you already did)
print("Rows:\n", rijen)
print("Columns:\n", kolommen)

# 4. PRINT THE SHAPE (This was the missing part!)
print("Shape of indices:", indices.shape)
print("Shape of rijen:", rijen.shape)

Rows:
 [[0 0 0 0 0 0]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [3 3 3 3 3 3]
 [4 4 4 4 4 4]]
Columns:
 [[0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]]
Shape of indices: (2, 5, 6)
Shape of rijen: (5, 6)


### Oefening 1.2 — Afstand tot het controlecentrum (broadcasting)

Het controlecentrum staat op positie `(2, 3)`. Bereken de **Euclidische afstand** van elke module tot het controlecentrum met broadcasting.

Formule: `sqrt((rij - 2)^2 + (kolom - 3)^2)`

Sla het resultaat op in een variabele `afstanden`. Print de afstanden afgerond op 2 decimalen.

*Tip: je hoeft geen loop te schrijven!*

In [4]:
# Oefening 1.2 — Jouw code hier

# compute distances
afstanden = np.sqrt((rijen - 2)**2 + (kolommen - 3)**2)

# print rounded result
print(np.round(afstanden, 2))


[[3.61 2.83 2.24 2.   2.24 2.83]
 [3.16 2.24 1.41 1.   1.41 2.24]
 [3.   2.   1.   0.   1.   2.  ]
 [3.16 2.24 1.41 1.   1.41 2.24]
 [3.61 2.83 2.24 2.   2.24 2.83]]


### Oefening 1.3 — Signaalsterkte berekenen (broadcasting met scalar)

De signaalsterkte van het controlecentrum naar elke module neemt af met het kwadraat van de afstand. De basissterkte is **100**.

Formule: `signaal = 100 / (1 + afstand^2)`

Bereken de signaalsterkte voor elke module. Sla op in `signaalsterkte` en print het resultaat afgerond op 1 decimaal.

In [5]:
# Oefening 1.3 — Jouw code hier

# compute signal strength
signaalsterkte = 100 / (1 + afstanden**2)

# print rounded to 1 decimal
print(np.round(signaalsterkte, 1))

[[  7.1  11.1  16.7  20.   16.7  11.1]
 [  9.1  16.7  33.3  50.   33.3  16.7]
 [ 10.   20.   50.  100.   50.   20. ]
 [  9.1  16.7  33.3  50.   33.3  16.7]
 [  7.1  11.1  16.7  20.   16.7  11.1]]


---
## Deel 2: Temperatuurmetingen (Broadcasting & Reshape)

De kolonie heeft **4 kassen** die voedsel produceren. Elke kas wordt **3 keer per dag** gemeten (ochtend, middag, avond) gedurende **7 dagen**. De data is opgeslagen in een 3D array met shape `(4, 7, 3)` — (kas, dag, meting).

### Oefening 2.1 — Data genereren

Genereer een 3D array `temperaturen` met shape `(4, 7, 3)` met willekeurige temperaturen (floats) tussen **18.0** en **28.0** graden. Gebruik de `rng` die al gedefinieerd is.

*Tip: `rng.uniform(low, high, size=...)`*

In [58]:
# Oefening 2.1 — Jouw code hier
import numpy as np

rng = np.random.default_rng(2087)
temperaturen = rng.uniform(18.0, 28.0, size=(4, 7, 3))

print(temperaturen)
print(temperaturen.shape)


[[[22.17747125 23.82578299 18.15633726]
  [20.57025001 22.04257386 24.64561552]
  [19.89922046 18.18701634 23.69817181]
  [24.71823616 22.67222684 19.49892183]
  [25.50600355 26.27829095 22.04537858]
  [18.7524349  18.52477184 24.65289002]
  [19.29213467 27.30545859 23.76327392]]

 [[23.83558702 24.22750122 20.37216618]
  [21.73460665 24.42199928 26.20724366]
  [21.42175173 20.5086082  19.41444738]
  [21.48984235 23.29866835 24.298261  ]
  [21.91107684 27.149768   22.78892326]
  [27.5230253  23.1924186  27.3951787 ]
  [26.7294777  24.80766363 27.5830316 ]]

 [[26.86274546 20.99183297 27.57647093]
  [21.10688899 23.32762649 26.43693978]
  [21.33205194 26.01291938 20.20364224]
  [24.62069143 24.30662689 21.81364302]
  [25.44443453 19.68334267 19.93125677]
  [19.57927831 27.75200068 26.96941168]
  [18.1868552  18.2918654  18.02967703]]

 [[21.87326211 22.84462795 20.82993624]
  [27.662112   26.2954667  24.82396769]
  [18.01088046 24.04660127 20.65242318]
  [21.52839529 19.3487529  20.8454

### Oefening 2.2 — Kalibratiecorrectie per kas (broadcasting met reshape)

De sensoren in de 4 kassen zijn niet perfect gekalibreerd. De correctiewaarden per kas zijn:

```python
correctie = np.array([0.5, -0.3, 0.8, -0.1])  # per kas
```

Pas deze correctie toe op **alle** temperatuurmetingen door `correctie` op te tellen bij `temperaturen`. 

**Let op:** de correctie heeft shape `(4,)` en temperaturen heeft shape `(4, 7, 3)`. Je zult `correctie` moeten **reshapen** zodat broadcasting werkt over de juiste as (de eerste as = kas).

Sla het resultaat op in `temp_gekalibreerd`.

In [59]:
correctie = np.array([0.5, -0.3, 0.8, -0.1])

# apply broadcasting by reshaping correction to match (kas, dag, meting)
temp_gekalibreerd = temperaturen + correctie.reshape(4, 1, 1)

# print result
print(temp_gekalibreerd)
print(temp_gekalibreerd.shape)

[[[22.67747125 24.32578299 18.65633726]
  [21.07025001 22.54257386 25.14561552]
  [20.39922046 18.68701634 24.19817181]
  [25.21823616 23.17222684 19.99892183]
  [26.00600355 26.77829095 22.54537858]
  [19.2524349  19.02477184 25.15289002]
  [19.79213467 27.80545859 24.26327392]]

 [[23.53558702 23.92750122 20.07216618]
  [21.43460665 24.12199928 25.90724366]
  [21.12175173 20.2086082  19.11444738]
  [21.18984235 22.99866835 23.998261  ]
  [21.61107684 26.849768   22.48892326]
  [27.2230253  22.8924186  27.0951787 ]
  [26.4294777  24.50766363 27.2830316 ]]

 [[27.66274546 21.79183297 28.37647093]
  [21.90688899 24.12762649 27.23693978]
  [22.13205194 26.81291938 21.00364224]
  [25.42069143 25.10662689 22.61364302]
  [26.24443453 20.48334267 20.73125677]
  [20.37927831 28.55200068 27.76941168]
  [18.9868552  19.0918654  18.82967703]]

 [[21.77326211 22.74462795 20.72993624]
  [27.562112   26.1954667  24.72396769]
  [17.91088046 23.94660127 20.55242318]
  [21.42839529 19.2487529  20.7454

### Oefening 2.3 — Daggewichten toepassen (broadcasting met vector)

De ochtend-, middag- en avondmetingen zijn niet even belangrijk. De gewichten zijn:

```python
gewichten = np.array([0.25, 0.50, 0.25])  # ochtend, middag, avond
```

Bereken voor elke kas en elke dag de **gewogen temperatuur** door `temp_gekalibreerd` element-wise te vermenigvuldigen met `gewichten` en vervolgens te sommeren over de laatste as (`axis=2`).

Het resultaat `temp_gewogen` moet shape `(4, 7)` hebben — de gewogen gemiddelde temperatuur per kas per dag.

In [60]:
gewichten = np.array([0.25, 0.50, 0.25])

# Oefening 2.3 — Jouw code hier
# element-wise multiplication + sum over measurement axis
temp_gewogen = np.sum(temp_gekalibreerd * gewichten, axis=2)

# print result
print(temp_gewogen)
print(temp_gewogen.shape)


[[22.49634362 22.82525331 20.49285623 22.89040292 25.52699101 20.61371715
  24.91658144]
 [22.86568891 23.89646222 20.16335388 22.79636001 24.44988402 25.0257603
  25.68195914]
 [24.90572058 24.34977044 24.19038323 24.56189706 21.98559416 26.31317284
  19.00006576]
 [21.99811357 26.16925327 21.58912655 20.16782924 23.13867454 24.00022184
  23.95183778]]
(4, 7)


---
## Deel 3: Alarmsysteem (Boolean Masks & np.where)

De gewogen temperaturen uit Deel 2 worden nu gebruikt door het alarmsysteem. Er zijn drie zones:

| Zone | Temperatuurbereik | Status |
|------|------------------|--------|
| Veilig | 20.0 - 25.0 | OK |
| Waarschuwing | 18.0-20.0 of 25.0-27.0 | LET OP |
| Alarm | < 18.0 of > 27.0 | ALARM |

### Oefening 3.1 — Veilige metingen filteren

Maak een boolean mask `mask_veilig` die `True` is waar `temp_gewogen` tussen **20.0 en 25.0** ligt (grenzen inclusief).

- Hoeveel metingen zijn veilig? (Gebruik `np.sum` of `.sum()` op de mask)
- Print alle veilige temperatuurwaarden.

In [61]:
# Oefening 3.1 — Jouw code hier
# create boolean mask for safe temperatures (inclusive range)
mask_veilig = (temp_gewogen >= 20.0) & (temp_gewogen <= 25.0)

# count how many safe measurements
aantal_veilig = np.sum(mask_veilig)

# print results
print("Aantal veilige metingen:", aantal_veilig)
print("Veilige temperaturen:", temp_gewogen[mask_veilig])


Aantal veilige metingen: 22
Veilige temperaturen: [22.49634362 22.82525331 20.49285623 22.89040292 20.61371715 24.91658144
 22.86568891 23.89646222 20.16335388 22.79636001 24.44988402 24.90572058
 24.34977044 24.19038323 24.56189706 21.98559416 21.99811357 21.58912655
 20.16782924 23.13867454 24.00022184 23.95183778]


### Oefening 3.2 — Gecombineerde mask: alarm-situaties

Maak een mask `mask_alarm` die `True` is waar de temperatuur **lager dan 18.0 OF hoger dan 27.0** is.

- Print welke temperaturen in alarm-status zijn.
- Gebruik `~` om ook een mask `mask_geen_alarm` te maken en verifieer dat de aantallen kloppen (alarm + geen_alarm = totaal).

In [62]:
# Oefening 3.2 — Jouw code hier

# mask for alarm: too cold OR too hot
mask_alarm = (temp_gewogen < 18.0) | (temp_gewogen > 27.0)

# values in alarm
print("Alarm temperaturen:", temp_gewogen[mask_alarm])

# inverse mask (no alarm)
mask_geen_alarm = ~mask_alarm

# verification of counts
aantal_alarm = np.sum(mask_alarm)
aantal_geen_alarm = np.sum(mask_geen_alarm)
totaal = temp_gewogen.size

print("Aantal alarm:", aantal_alarm)
print("Aantal geen alarm:", aantal_geen_alarm)
print("Totaal:", totaal)

# check correctness
print("Controle klopt:", aantal_alarm + aantal_geen_alarm == totaal)


Alarm temperaturen: []
Aantal alarm: 0
Aantal geen alarm: 28
Totaal: 28
Controle klopt: True


### Oefening 3.3 — Statuslabels toekennen met np.where

Gebruik **geneste `np.where`** om een array `status` te maken met dezelfde shape als `temp_gewogen`, waarin elke meting het label krijgt:
- `'ALARM'` als temp < 18.0 of temp > 27.0
- `'LET OP'` als temp tussen 18.0-20.0 of 25.0-27.0 (exclusief de alarm-grenzen)
- `'OK'` in alle andere gevallen

Print het resultaat.

In [63]:
# Oefening 3.3 — Jouw code hier
status = np.where(
    (temp_gewogen < 18.0) | (temp_gewogen > 27.0),
    "ALARM",
    np.where(
        ((temp_gewogen >= 18.0) & (temp_gewogen < 20.0)) |
        ((temp_gewogen > 25.0) & (temp_gewogen <= 27.0)),
        "LET OP",
        "OK"
    )
)

print(status)


[['OK' 'OK' 'OK' 'OK' 'LET OP' 'OK' 'OK']
 ['OK' 'OK' 'OK' 'OK' 'OK' 'LET OP' 'LET OP']
 ['OK' 'OK' 'OK' 'OK' 'OK' 'LET OP' 'LET OP']
 ['OK' 'LET OP' 'OK' 'OK' 'OK' 'OK' 'OK']]


### Oefening 3.4 — Defecte sensoren opsporen (np.isnan)

Sommige sensoren zijn defect en geven `NaN` terug. Hieronder staat een nieuwe meting met enkele ontbrekende waarden.

```python
metingen_raw = np.array([22.1, np.nan, 24.5, 19.8, np.nan, 26.3, 21.0, np.nan, 23.4, 20.1])
```

1. Maak een mask voor de ontbrekende waarden met `np.isnan`.
2. Hoeveel sensoren zijn defect (tel het aantal NaN waarden)?
3. Maak een array `metingen_clean` met alleen de geldige (niet-NaN) waarden.
4. Bereken het gemiddelde van de geldige waarden.

In [64]:
metingen_raw = np.array([22.1, np.nan, 24.5, 19.8, np.nan, 26.3, 21.0, np.nan, 23.4, 20.1])

# Oefening 3.4 — Jouw code hier

# 1. mask for NaN values
mask_nan = np.isnan(metingen_raw)

# 2. count defective sensors
aantal_defect = np.sum(mask_nan)

# 3. keep only valid values
metingen_clean = metingen_raw[~mask_nan]

# 4. compute mean of valid values
gemiddelde = np.mean(metingen_clean)

# print results
print("Defecte sensoren:", aantal_defect)
print("Schone metingen:", metingen_clean)
print("Gemiddelde:", gemiddelde)


Defecte sensoren: 3
Schone metingen: [22.1 24.5 19.8 26.3 21.  23.4 20.1]
Gemiddelde: 22.457142857142856


---
## Deel 4: Voorraadbeheer (Fancy Indexing & np.add.at)

De kolonie heeft een centraal magazijn met **20 verschillende voorraadcategorieën** (zuurstof, water, voedsel, medicijnen, reserveonderdelen, ...). De voorraad wordt bijgehouden in een array.

### Oefening 4.1 — Voorraadstand opvragen

Hieronder staat de huidige voorraad. Gebruik **fancy indexing** om in één keer de voorraad op te vragen van categorieën **[0, 3, 7, 12, 18]** (de kritieke categorieën).

```python
voorraad = np.array([500, 320, 180, 45, 890, 230, 670, 15, 440, 310,
                     520, 95, 8, 760, 420, 155, 380, 620, 25, 490])
```

In [65]:
voorraad = np.array([500, 320, 180, 45, 890, 230, 670, 15, 440, 310,
                     520, 95, 8, 760, 420, 155, 380, 620, 25, 490])

# Oefening 4.1 — Jouw code hier
# critical categories
kritieke_categorieen = [0, 3, 7, 12, 18]

# fancy indexing
kritieke_voorraad = voorraad[kritieke_categorieen]

print(kritieke_voorraad)

[500  45  15   8  25]


### Oefening 4.2 — Fancy indexing op een 2D logboek

Het verbruikslogboek van de afgelopen 4 weken (rijen) voor 6 categorieën (kolommen) ziet er zo uit:

```python
logboek = np.array([
    [50, 30, 20, 10,  5, 15],
    [45, 35, 25, 12,  8, 10],
    [55, 28, 22, 15,  3, 20],
    [60, 32, 18,  8,  6, 12]
])
```

1. Selecteer het verbruik van **week 0 en week 3** (fancy indexing op rijen).
2. Selecteer de specifieke elementen `(0,2)`, `(1,4)` en `(3,1)` met rij- en kolom-index-arrays.
3. Selecteer **week 1 en 2**, maar alleen **kolommen 0 t/m 2** (combined: fancy indexing + slice).

In [66]:
logboek = np.array([
    [50, 30, 20, 10,  5, 15],
    [45, 35, 25, 12,  8, 10],
    [55, 28, 22, 15,  3, 20],
    [60, 32, 18,  8,  6, 12]
])

# Oefening 4.2 — Jouw code hier
# 1. Week 0 en week 3
print(logboek[[0, 3]])

# 2. Elementen (0,2), (1,4), (3,1)
rijen = np.array([0, 1, 3])
kolommen = np.array([2, 4, 1])

print(logboek[rijen, kolommen])

# 3. Week 1-2, kolommen 0 t/m 2
print(logboek[[1, 2], 0:3])


[[50 30 20 10  5 15]
 [60 32 18  8  6 12]]
[20  8 32]
[[45 35 25]
 [55 28 22]]


### Oefening 4.3 — Bevoorrading verwerken met np.add.at

Er komt een bevoorradingsschip aan! De leveringen worden per categorie-index geleverd. Sommige categorieën krijgen **meerdere leveringen**:

```python
levering_indices = np.array([0, 3, 3, 7, 7, 7, 12, 12, 18, 18])
levering_hoeveelheden = np.array([100, 50, 50, 30, 30, 30, 200, 200, 75, 75])
```

1. Maak een kopie van `voorraad` genaamd `voorraad_nieuw`.
2. Gebruik `np.add.at` om de leveringen correct te verwerken (herhaalde indices!).
3. Print de voorraad van de kritieke categorieën `[0, 3, 7, 12, 18]` voor en na de levering.

**Waarom werkt `voorraad_nieuw[levering_indices] += levering_hoeveelheden` hier NIET correct?**

In [67]:
levering_indices = np.array([0, 3, 3, 7, 7, 7, 12, 12, 18, 18])
levering_hoeveelheden = np.array([100, 50, 50, 30, 30, 30, 200, 200, 75, 75])

# Oefening 4.3 — Jouw code hier
# copy original stock
voorraad_nieuw = voorraad.copy()

# before delivery
print("Voor levering:", voorraad_nieuw[[0, 3, 7, 12, 18]])

# correct accumulation
np.add.at(voorraad_nieuw, levering_indices, levering_hoeveelheden)

# after delivery
print("Na levering:", voorraad_nieuw[[0, 3, 7, 12, 18]])


Voor levering: [500  45  15   8  25]
Na levering: [600 145 105 408 175]


### Oefening 4.4 — Verbruik per categorie tellen (data binning)

Het verbruikslogboek bevat individuele verbruiksgebeurtenissen. Elke gebeurtenis hoort bij een categorie (0-19):

```python
verbruik_events = rng.integers(0, 20, size=200)  # 200 events, categorie 0-19
```

1. Maak een lege teller-array `teller` van 20 nullen (integers).
2. Gebruik `np.add.at` om te tellen hoe vaak elke categorie voorkomt.
3. Print de teller en verifieer dat de som 200 is.
4. Welke categorie wordt het vaakst verbruikt? (Gebruik `np.argmax`)

In [68]:
verbruik_events = rng.integers(0, 20, size=200)

# Oefening 4.4 — Jouw code hier

# 1. empty counter array
teller = np.zeros(20, dtype=int)

# 2. count occurrences using np.add.at
np.add.at(teller, verbruik_events, 1)

# 3. print results
print("Teller per categorie:", teller)
print("Totaal aantal events:", np.sum(teller))

# 4. most frequent category
meest_gebruikt = np.argmax(teller)
print("Meest gebruikte categorie:", meest_gebruikt)


Teller per categorie: [10  8 16  9  5 10 13 12 12  9 14  5 12  7 14 14  8  8  7  7]
Totaal aantal events: 200
Meest gebruikte categorie: 2


---
## Deel 5: Bemanning Rangschikken (Sorting & Partitioning)

De kolonie heeft 15 bemanningsleden. Elk bemanningslid heeft een **fitnessscore** (0-100) die wekelijks wordt gemeten. De commandant moet beslissingen nemen op basis van deze scores.

### Oefening 5.1 — Scores sorteren

```python
fitness = np.array([78, 92, 45, 88, 67, 55, 91, 73, 82, 60, 95, 38, 71, 84, 50])
namen = np.array(['Ada', 'Ben', 'Cas', 'Deb', 'Eva', 'Fin', 'Gia', 'Hal', 'Ivy', 'Jan', 'Kim', 'Leo', 'Mia', 'Nik', 'Oli'])
```

1. Sorteer de fitnessscores van laag naar hoog met `np.sort`. Sla op in `scores_sorted`.
2. Gebruik `np.argsort` om de **namen** te sorteren op basis van hun fitnessscore (laag → hoog).
3. Print de top 5 namen met hoogste fitnessscore (hint: sorteer en neem de laatste 5, of keer de volgorde om).

In [69]:
fitness = np.array([78, 92, 45, 88, 67, 55, 91, 73, 82, 60, 95, 38, 71, 84, 50])
namen = np.array(['Ada', 'Ben', 'Cas', 'Deb', 'Eva', 'Fin', 'Gia', 'Hal', 'Ivy', 'Jan', 'Kim', 'Leo', 'Mia', 'Nik', 'Oli'])

# Oefening 5.1 — Jouw code hier
# 1. Sorteer scores
scores_sorted = np.sort(fitness)
print("Gesorteerde scores:", scores_sorted)
# 2. Sorteer namen op basis van score
indices = np.argsort(fitness)
namen_sorted = namen[indices]
print("Namen gesorteerd op score:", namen_sorted)
# 3. Top 5 namen
top5_namen = namen_sorted[-5:]
print("Top 5 hoogste scores:", top5_namen)


Gesorteerde scores: [38 45 50 55 60 67 71 73 78 82 84 88 91 92 95]
Namen gesorteerd op score: ['Leo' 'Cas' 'Oli' 'Fin' 'Jan' 'Eva' 'Mia' 'Hal' 'Ada' 'Ivy' 'Nik' 'Deb'
 'Gia' 'Ben' 'Kim']
Top 5 hoogste scores: ['Nik' 'Deb' 'Gia' 'Ben' 'Kim']


### Oefening 5.2 — Snel de zwakste 3 vinden (np.argpartition)

De commandant wil snel weten welke **3 bemanningsleden** de laagste fitnessscore hebben, zonder de hele array te sorteren.

1. Gebruik `np.argpartition(fitness, 3)` om de indices van de 3 laagste scores te vinden.
2. Print de namen en scores van deze 3 bemanningsleden. (mag met een loop)
3. Gebruik ook `np.partition` met negatief k (`-3`) om de **3 hoogste** scores te vinden.

**Waarom is `np.argpartition` efficiënter dan `np.argsort` voor deze taak?** (Beantwoord als commentaar)

In [70]:
# Oefening 5.2 — Jouw code hier
# 1. indices of 3 lowest scores
indices_laagste = np.argpartition(fitness, 3)[:3]

print("3 laagste scores:")
for i in indices_laagste:
    print(namen[i], fitness[i])

# 2. 3 highest scores using partition
hoogste_scores = np.partition(fitness, -3)[-3:]
print("3 hoogste scores:", hoogste_scores)


3 laagste scores:
Leo 38
Cas 45
Oli 50
3 hoogste scores: [91 92 95]


### Oefening 5.3 — 2D sortering: wekelijkse scores

De fitnessscores van 5 bemanningsleden over 4 weken:

```python
wekelijks = np.array([
    [78, 82, 75, 88],   # Ada
    [92, 85, 90, 87],   # Ben
    [45, 50, 42, 55],   # Cas
    [88, 91, 86, 93],   # Deb
    [67, 70, 65, 72]    # Eva
])
```

1. Sorteer elke **rij** (de wekelijkse scores per persoon) met `np.sort` langs `axis=1`.
2. Sorteer elke **kolom** (de scores per week, over alle personen) met `np.sort` langs `axis=0`.
3. Wat is het verschil in resultaat?

In [71]:
wekelijks = np.array([
    [78, 82, 75, 88],
    [92, 85, 90, 87],
    [45, 50, 42, 55],
    [88, 91, 86, 93],
    [67, 70, 65, 72]
])

# Oefening 5.3 — Jouw code hier
# 1. Sorteer per rij (axis=1)
rij_sorted = np.sort(wekelijks, axis=1)
print("Rijen gesorteerd:\n", rij_sorted)

# 2. Sorteer per kolom (axis=0)
kolom_sorted = np.sort(wekelijks, axis=0)
print("Kolommen gesorteerd:\n", kolom_sorted)
# 3. Wat is het verschil?
#The difference is that sorting along axis=1 sorts each row independently, meaning each person's weekly scores are ordered. Sorting along axis=0 sorts each column independently, meaning the scores are ordered across people for each week.


Rijen gesorteerd:
 [[75 78 82 88]
 [85 87 90 92]
 [42 45 50 55]
 [86 88 91 93]
 [65 67 70 72]]
Kolommen gesorteerd:
 [[45 50 42 55]
 [67 70 65 72]
 [78 82 75 87]
 [88 85 86 88]
 [92 91 90 93]]


---
## Deel 6: Bemanningsbestand (Structured Arrays)

Alle bemanningsgegevens worden opgeslagen in een structured array. Dit is het hart van het personeelssysteem van de kolonie.

### Oefening 6.1 — Structured array aanmaken

Maak een structured array `bemanning` met de volgende velden:

| Veld | Dtype | Beschrijving |
|------|-------|-------------|
| `naam` | `U20` | Naam |
| `leeftijd` | `i4` | Leeftijd |
| `functie` | `U20` | Functie |
| `fitness` | `f8` | Fitnessscore |
| `missies` | `i4` | Aantal voltooide missies |

Vul de array met deze data:

| Naam | Leeftijd | Functie | Fitness | Missies |
|------|----------|---------|---------|---------|
| Ada | 34 | Ingenieur | 78.5 | 12 |
| Ben | 29 | Piloot | 92.0 | 8 |
| Cas | 41 | Arts | 45.3 | 22 |
| Deb | 36 | Bioloog | 88.1 | 15 |
| Eva | 27 | Geoloog | 67.4 | 5 |
| Fin | 45 | Commandant | 55.9 | 31 |
| Gia | 31 | Piloot | 91.2 | 10 |
| Hal | 38 | Ingenieur | 73.6 | 18 |

In [72]:
# Oefening 6.1 — Jouw code hier

# define structured dtype
dtype = [
    ('naam', 'U20'),
    ('leeftijd', 'i4'),
    ('functie', 'U20'),
    ('fitness', 'f8'),
    ('missies', 'i4')
]

# create structured array
bemanning = np.array([
    ('Ada', 34, 'Ingenieur', 78.5, 12),
    ('Ben', 29, 'Piloot', 92.0, 8),
    ('Cas', 41, 'Arts', 45.3, 22),
    ('Deb', 36, 'Bioloog', 88.1, 15),
    ('Eva', 27, 'Geoloog', 67.4, 5),
    ('Fin', 45, 'Commandant', 55.9, 31),
    ('Gia', 31, 'Piloot', 91.2, 10),
    ('Hal', 38, 'Ingenieur', 73.6, 18)
], dtype=dtype)

# print result
print(bemanning)

[('Ada', 34, 'Ingenieur', 78.5, 12) ('Ben', 29, 'Piloot', 92. ,  8)
 ('Cas', 41, 'Arts', 45.3, 22) ('Deb', 36, 'Bioloog', 88.1, 15)
 ('Eva', 27, 'Geoloog', 67.4,  5) ('Fin', 45, 'Commandant', 55.9, 31)
 ('Gia', 31, 'Piloot', 91.2, 10) ('Hal', 38, 'Ingenieur', 73.6, 18)]


### Oefening 6.2 — Velden opvragen en filteren

Gebruik de structured array `bemanning` om het volgende te doen:

1. Print alle **namen** (veld selectie).
2. Print de **gemiddelde leeftijd** van de bemanning.
3. Filter alle bemanningsleden met een **fitness hoger dan 80** en print hun namen en fitness.
4. Filter alle **Piloten** en print hun namen en aantal missies.
5. Combineer: filter bemanningsleden die **ouder zijn dan 35 EN meer dan 15 missies** hebben voltooid.

In [73]:
# Oefening 6.2 — Jouw code hier
# 1. Alle namen
print("Namen:", bemanning['naam'])
# 2. Gemiddelde leeftijd
gem_leeftijd = np.mean(bemanning['leeftijd'])
print("Gemiddelde leeftijd:", gem_leeftijd)
# 3. Fitness > 80
mask_fit = bemanning['fitness'] > 80
print("Fitness > 80:")
print(bemanning['naam'][mask_fit], bemanning['fitness'][mask_fit])
# 4. Alle piloten
mask_piloot = bemanning['functie'] == 'Piloot'
print("Piloten:")
print(bemanning['naam'][mask_piloot], bemanning['missies'][mask_piloot])
# 5. Ouder dan 35 EN meer dan 15 missies
mask_combined = (bemanning['leeftijd'] > 35) & (bemanning['missies'] > 15)
print("Ouder dan 35 en >15 missies:")
print(bemanning[mask_combined])


Namen: ['Ada' 'Ben' 'Cas' 'Deb' 'Eva' 'Fin' 'Gia' 'Hal']
Gemiddelde leeftijd: 35.125
Fitness > 80:
['Ben' 'Deb' 'Gia'] [92.  88.1 91.2]
Piloten:
['Ben' 'Gia'] [ 8 10]
Ouder dan 35 en >15 missies:
[('Cas', 41, 'Arts', 45.3, 22) ('Fin', 45, 'Commandant', 55.9, 31)
 ('Hal', 38, 'Ingenieur', 73.6, 18)]


### Oefening 6.3 — Bonus berekenen met np.where

De commandant wil een bonus toekennen:
- Bemanningsleden met **fitness >= 80** krijgen een bonus van **+5 missies**.
- Bemanningsleden met **fitness < 50** krijgen **verplichte rust** (missies worden op **0** gezet).
- Alle anderen blijven ongewijzigd.

1. Maak een kopie van `bemanning` genaamd `bemanning_updated`.
2. Gebruik (geneste) `np.where` om het veld `missies` aan te passen volgens bovenstaande regels.
3. Print voor elk bemanningslid de naam, fitness en het (nieuwe) aantal missies.

In [74]:
# Oefening 6.3 — Jouw code hier

# 1. make a copy
bemanning_updated = bemanning.copy()

# 2. update missions using nested np.where
bemanning_updated['missies'] = np.where(
    bemanning['fitness'] >= 80,
    bemanning['missies'] + 5,
    np.where(
        bemanning['fitness'] < 50,
        0,
        bemanning['missies']
    )
)

# 3. print results
for persoon in bemanning_updated:
    print(persoon['naam'], persoon['fitness'], persoon['missies'])


Ada 78.5 12
Ben 92.0 13
Cas 45.3 0
Deb 88.1 20
Eva 67.4 5
Fin 55.9 31
Gia 91.2 15
Hal 73.6 18


---
## Deel 7: Energiebeheer (Structured Arrays — Geavanceerd)

De kolonie heeft 6 energiemodules. Elke module wordt dagelijks gemeten (ma t/m zo). Net als bij de boerderijen uit les 12 moet je facturatie berekenen.

### Oefening 7.1 — Energiedata opzetten

Maak een structured array `energie` met de volgende velden:

| Veld | Dtype |
|------|-------|
| `module` | `U20` |
| `ma` | `f8` |
| `di` | `f8` |
| `wo` | `f8` |
| `do` | `f8` |
| `vr` | `f8` |
| `za` | `f8` |
| `zo` | `f8` |
| `factuur` | `f8` |

Vul met deze data (factuur begint op 0):

| Module | Ma | Di | Wo | Do | Vr | Za | Zo |
|--------|-----|-----|-----|-----|-----|-----|-----|
| Woonunit_A | 500 | 510 | 520 | 530 | 540 | 550 | 560 |
| Woonunit_B | 600 | 580 | 570 | 550 | 530 | 520 | 510 |
| Lab_Alpha | 900 | 920 | 950 | 980 | 1000 | 800 | 1050 |
| Lab_Beta | 750 | 740 | 730 | 720 | 710 | 700 | 690 |
| Kas_1 | 300 | 310 | 305 | 315 | 320 | 310 | 325 |
| Energie_HQ | 200 | 200 | 200 | 200 | 200 | 200 | 200 |

In [75]:
# Oefening 7.1 — Jouw code hier
import numpy as np

# define dtype
dtype = [
    ('module', 'U20'),
    ('ma', 'f8'),
    ('di', 'f8'),
    ('wo', 'f8'),
    ('do', 'f8'),
    ('vr', 'f8'),
    ('za', 'f8'),
    ('zo', 'f8'),
    ('factuur', 'f8')
]

# create structured array
energie = np.array([
    ('Woonunit_A', 500, 510, 520, 530, 540, 550, 560, 0.0),
    ('Woonunit_B', 600, 580, 570, 550, 530, 520, 510, 0.0),
    ('Lab_Alpha', 900, 920, 950, 980, 1000, 800, 1050, 0.0),
    ('Lab_Beta', 750, 740, 730, 720, 710, 700, 690, 0.0),
    ('Kas_1', 300, 310, 305, 315, 320, 310, 325, 0.0),
    ('Energie_HQ', 200, 200, 200, 200, 200, 200, 200, 0.0)
], dtype=dtype)

# print result
print(energie)


[('Woonunit_A', 500., 510., 520., 530.,  540., 550.,  560., 0.)
 ('Woonunit_B', 600., 580., 570., 550.,  530., 520.,  510., 0.)
 ('Lab_Alpha', 900., 920., 950., 980., 1000., 800., 1050., 0.)
 ('Lab_Beta', 750., 740., 730., 720.,  710., 700.,  690., 0.)
 ('Kas_1', 300., 310., 305., 315.,  320., 310.,  325., 0.)
 ('Energie_HQ', 200., 200., 200., 200.,  200., 200.,  200., 0.)]


### Oefening 7.2 — Facturatie berekenen

Bereken de factuur in 3 stappen (net als in file 12):

**Stap 1:** Basisfactuur = `zo - ma` (toename over de week).

**Stap 2:** Boete: als `zo > vr` (weekendverbruik stijgt), tel **+20** op bij de factuur. Gebruik `np.where`.

**Stap 3:** Korting: als het verbruik doorheen de werkweek **daalt** (`ma >= di >= wo >= do >= vr`), krijgt de module **15% korting** op de factuur. Gebruik een gecombineerde boolean mask en `np.where`.

Print na elke stap de modulenaam en factuur.

In [76]:
# Oefening 7.2 — Jouw code hier
# Stap 1: Basisfactuur
energie['factuur'] = energie['zo'] - energie['ma']

print("Na stap 1 (basisfactuur):")
for e in energie:
    print(e['module'], e['factuur'])

# Stap 2: Boete weekendverbruik
energie['factuur'] = np.where(
    energie['zo'] > energie['vr'],
    energie['factuur'] + 20,
    energie['factuur']
)

print("\nNa stap 2 (boete):")
for e in energie:
    print(e['module'], e['factuur'])
# Stap 3: Korting dalend weekverbruik
mask_daling = (
    (energie['ma'] >= energie['di']) &
    (energie['di'] >= energie['wo']) &
    (energie['wo'] >= energie['do']) &
    (energie['do'] >= energie['vr'])
)

energie['factuur'] = np.where(
    mask_daling,
    energie['factuur'] * 0.85,  # 15% discount
    energie['factuur']
)

print("\nNa stap 3 (korting):")
for e in energie:
    print(e['module'], e['factuur'])

Na stap 1 (basisfactuur):
Woonunit_A 60.0
Woonunit_B -90.0
Lab_Alpha 150.0
Lab_Beta -60.0
Kas_1 25.0
Energie_HQ 0.0

Na stap 2 (boete):
Woonunit_A 80.0
Woonunit_B -90.0
Lab_Alpha 170.0
Lab_Beta -60.0
Kas_1 45.0
Energie_HQ 0.0

Na stap 3 (korting):
Woonunit_A 80.0
Woonunit_B -76.5
Lab_Alpha 170.0
Lab_Beta -51.0
Kas_1 45.0
Energie_HQ 0.0


---
## Deel 8: Missiedossiers (Structured Arrays — Subarrays & RecordArrays)

### Oefening 8.1 — Structured array met subarray

De kolonie houdt missiedossiers bij. Elke missie heeft een naam, een moeilijkheidsgraad, en de **scores van 4 beoordelaars**.

Maak een structured array `missies` met dtype:

| Veld | Dtype | Beschrijving |
|------|-------|-------------|
| `naam` | `U30` | Missienaam |
| `moeilijkheid` | `i4` | 1-10 |
| `scores` | `f8` met subarray `(4,)` | Scores van 4 beoordelaars |

Vul met deze data:

| Missie | Moeilijkheid | Scores |
|--------|-------------|--------|
| Kraterverkenning | 7 | [8.5, 9.0, 7.5, 8.0] |
| Waterwinning | 5 | [9.0, 8.5, 9.5, 9.0] |
| Noodlanding_oefening | 9 | [6.0, 7.0, 5.5, 6.5] |
| Kasuitbreiding | 4 | [9.5, 9.0, 9.5, 10.0] |
| Zonnepaneel_reparatie | 6 | [7.0, 7.5, 8.0, 7.0] |

Vervolgens:
1. Print alle scores als 2D array.
2. Bereken de **gemiddelde score per missie** (gebruik `.mean(axis=1)` op het scores-veld).
3. Welke missie heeft de hoogste gemiddelde score? (Gebruik `np.argmax`)

In [77]:
# Oefening 8.1 — Jouw code hier
# define dtype with subarray
dtype = [
    ('naam', 'U30'),
    ('moeilijkheid', 'i4'),
    ('scores', 'f8', (4,))
]

# create structured array
missies = np.array([
    ('Kraterverkenning', 7, [8.5, 9.0, 7.5, 8.0]),
    ('Waterwinning', 5, [9.0, 8.5, 9.5, 9.0]),
    ('Noodlanding_oefening', 9, [6.0, 7.0, 5.5, 6.5]),
    ('Kasuitbreiding', 4, [9.5, 9.0, 9.5, 10.0]),
    ('Zonnepaneel_reparatie', 6, [7.0, 7.5, 8.0, 7.0])
], dtype=dtype)

# 1. print scores as 2D array
scores = missies['scores']
print("Scores (2D):\n", scores)

# 2. average score per mission
gemiddelden = scores.mean(axis=1)
print("Gemiddelde score per missie:", gemiddelden)

# 3. mission with highest average
beste_index = np.argmax(gemiddelden)
beste_missie = missies['naam'][beste_index]

print("Beste missie:", beste_missie)


Scores (2D):
 [[ 8.5  9.   7.5  8. ]
 [ 9.   8.5  9.5  9. ]
 [ 6.   7.   5.5  6.5]
 [ 9.5  9.   9.5 10. ]
 [ 7.   7.5  8.   7. ]]
Gemiddelde score per missie: [8.25  9.    6.25  9.5   7.375]
Beste missie: Kasuitbreiding


### Oefening 8.2 — RecordArray

Converteer de structured array `missies` naar een **RecordArray** met `missies.view(np.recarray)`.

1. Gebruik **punt-notatie** om de missienamen op te vragen (bijv. `record.naam`).
2. Gebruik punt-notatie om de moeilijkheidsgraden te printen.
3. Wat is het verschil tussen een structured array en een RecordArray qua syntax? (Beantwoord als commentaar)

In [78]:
# Oefening 8.2 — Jouw code hier
# 1. Convert to RecordArray
missies_rec = missies.view(np.recarray)

# 2. Use dot notation for names
print("Mission Names:", missies_rec.naam)

# 3. Use dot notation for difficulty levels
print("Difficulty Levels:", missies_rec.moeilijkheid)

# 4. The difference (as a comment):
# In a structured array, you access data using brackets and strings: array['field'].
# In a RecordArray, you can use dot notation: array.field.
# This makes the code cleaner and easier to read, similar to accessing an object's attributes.


Mission Names: ['Kraterverkenning' 'Waterwinning' 'Noodlanding_oefening' 'Kasuitbreiding'
 'Zonnepaneel_reparatie']
Difficulty Levels: [7 5 9 4 6]


---
## Deel 9: Eindmissie — Alles Samen

De commandant vraagt een volledig rapport. In deze laatste oefening combineer je alles wat je geleerd hebt.

### Oefening 9.1 — Missietoewijzing

De commandant wilt de **top 3 fitste** bemanningsleden (uit `bemanning` van Deel 6) toewijzen aan de **3 moeilijkste** missies (uit `missies` van Deel 8).


1. Gebruik `np.argsort` op het `fitness`-veld van `bemanning` om de indices van de top 3 fitste leden te vinden.
2. Gebruik `np.argsort` op het `moeilijkheid`-veld van `missies` om de indices van de 3 moeilijkste missies te vinden.
3. Print de toewijzing: welk bemanningslid gaat op welke missie? (tip: gebruik zip om de arrays te combineren)

Note: de berekeningen en sorteringen dienen met numpy te gebeuren. printen mag met loops

In [79]:
# Oefening 9.1 — Jouw code hier
# 1. Find indices of the 3 fittest crew members
# np.argsort goes low -> high, so we take the last 3 [-3:]
fitste_indices = np.argsort(bemanning['fitness'])[-3:]

# 2. Find indices of the 3 hardest missions
moeilijkste_indices = np.argsort(missies['moeilijkheid'])[-3:]

# 3. Get the names using those indices
top_crew_namen = bemanning['naam'][fitste_indices]
top_missie_namen = missies['naam'][moeilijkste_indices]

# 4. Print the assignment (highest fitness to highest difficulty)
# We flip them with [::-1] so the absolute #1 goes to the absolute hardest mission
for crew, missie in zip(top_crew_namen[::-1], top_missie_namen[::-1]):
    print(f"Astronaut {crew} is assigned to mission: {missie}")

Astronaut Ben is assigned to mission: Noodlanding_oefening
Astronaut Gia is assigned to mission: Kraterverkenning
Astronaut Deb is assigned to mission: Zonnepaneel_reparatie


### Oefening 9.2 — Kolonieoverzicht

Maak een **geneste structured array** voor een kolonierapport. Het rapport bevat per module:

| Veld | Dtype | Beschrijving |
|------|-------|-------------|
| `naam` | `U20` | Modulenaam |
| `locatie` | genest dtype met `rij` (`i4`) en `kolom` (`i4`) | Positie in het raster |
| `status` | `U10` | 'OK', 'LET OP' of 'ALARM' |

Maak de geneste dtype en vul de array met minstens **4 modules** naar keuze. Toon aan dat je de geneste velden kunt benaderen (bijv. `rapport['locatie']['rij']`).

In [80]:
# Oefening 9.2 — Jouw code hier

# 1. Define the "inner" folder (The Location)
locatie_dtype = [('rij', 'i4'), ('kolom', 'i4')]

# 2. Define the "outer" folder (The Report)
# Note how 'locatie' uses the dtype we just made above!
rapport_dtype = [
    ('naam', 'U20'),
    ('locatie', locatie_dtype),
    ('status', 'U10')
]

# 3. Fill the array with 4 modules
# We use extra parentheses (row, col) to group the location data
rapport_data = [
    ('Habitat_Alpha', (0, 0), 'OK'),
    ('Science_Lab', (2, 3), 'OK'),
    ('Solar_Array', (4, 5), 'WARNING'),
    ('Oxygen_Gen', (1, 2), 'ALARM')
]

rapport = np.array(rapport_data, dtype=rapport_dtype)

# 4. Demonstrate how to "drill down" into the data
print("All module names:", rapport['naam'])
print("All Row coordinates:", rapport['locatie']['rij'])
print("The status of the 3rd module:", rapport[2]['status'])

All module names: ['Habitat_Alpha' 'Science_Lab' 'Solar_Array' 'Oxygen_Gen']
All Row coordinates: [0 2 4 1]
The status of the 3rd module: WARNING


### Oefening 9.3 — Dichtstbijzijnde hulppost (alles samen)

Er is een noodgeval in de kolonie! Het noodsignaal komt van positie `(4, 1)` in het 5x6 raster. Er zijn 3 hulpposten op de volgende posities:

```python
hulpposten = np.array([[0, 0], [2, 5], [3, 2]])
noodpositie = np.array([4, 1])
```

1. Bereken de Euclidische afstand van de `noodpositie` tot elke hulppost met **broadcasting** (niet met een loop!).
2. Gebruik `np.argpartition` (of `np.argmin`) om de **dichtstbijzijnde** hulppost te vinden.
3. Print welke hulppost het dichtst bij is en hoe ver die is.

*Dit combineert broadcasting, afstandsberekening en partitioning/sorting — alles wat je geleerd hebt!*

In [81]:
hulpposten = np.array([[0, 0], [2, 5], [3, 2]])
noodpositie = np.array([4, 1])

# Oefening 9.3 — Jouw code hier

# Data provided for the emergency
hulpposten = np.array([[0, 0], [2, 5], [3, 2]])
noodpositie = np.array([4, 1])

# 1. Calculate the distance using broadcasting
# We subtract the emergency position [4, 1] from all three help station rows at once
differences = hulpposten - noodpositie

# 2. Square the differences and sum them along the columns (axis=1)
# Then take the square root to get the final Euclidean distances
distances = np.sqrt(np.sum(differences**2, axis=1))

# 3. Find the index of the smallest distance (the nearest station)
nearest_index = np.argmin(distances)

# 4. Print results
closest_station = hulpposten[nearest_index]
distance_value = distances[nearest_index]

print(f"The nearest help station is at location: {closest_station}")
print(f"The distance is: {distance_value:.2f} units")

The nearest help station is at location: [3 2]
The distance is: 1.41 units


# You made it! ;) 